# Takes about 6-7 hours.
# Opponents with known ratings from the CCRL Blitz list (Oct 10, 2026):
# https://computerchess.org.uk/ccrl/404/rating_list_all.html

[match]
tc = "30+0.3"
games_per_opponent = 320
concurrency = 10
openings = "../../../tests/data/positions.txt"
hash = 64
timemargin = 50

draw = { movenumber = 40, movecount = 8, score = 10 }
resign = { movecount = 4, score = 1000 }

[engine]
name = "Chrunch"
options = {}

[[opponent]]
name = "Berserk 4.1.0"
cmd = "berserk/berserk-4.1.0"
rating = 3133
rating_error = 17

[[opponent]]
name = "Halogen 9"
cmd = "halogen/halogen-9"
rating = 3168
rating_error = 16

[[opponent]]
name = "Stash 31.0"
cmd = "stash/stash-31.0"
rating = 3208
rating_error = 14
options = { "Move Overhead" = 100 }

[[opponent]]
name = "Weiss 1.4"
cmd = "weiss/weiss-1.4"
rating = 3255
rating_error = 16

[[opponent]]
name = "Stash 33.0"
cmd = "stash/stash-33.0"
rating = 3273
rating_error = 14
options = { "Move Overhead" = 100 }

[[opponent]]
name = "Weiss 2.0"
cmd = "weiss/weiss-2.0"
rating = 3319
rating_error = 8

[[opponent]]
name = "Berserk 4.4.0"
cmd = "berserk/berserk-4.4.0"
rating = 3334
rating_error = 14

[[opponent]]
name = "Stash 36.0"
cmd = "stash/stash-36.0"
rating = 3375
rating_error = 14
options = { "Move Overhead" = 100 }

[[opponent]]
name = "Stash 37.0"
cmd = "stash/stash-37.0"
rating = 3417
rating_error = 11
options = { "MoveOverhead" = 100 }

[[opponent]]
name = "Halogen 11"
cmd = "halogen/halogen-11"
rating = 3426
rating_error = 9
